title: Basti
description: >-
  Scala software developer. System engineer satellite mission planning. Rust. Arch.
repository: swsnr/swsnr.de

excerpt_separator: "<!--more-->"
show_excerpts: true

author:
  name: Basti
  email: sebastian@swsnr.de

# Build settings
markdown: kramdown

header_pages: []

theme: minima
minima:
  skin: solarized
  social_links:
    - platform: github
      user_url: https://github.com/swsnr
    - platform: linkedin
      user_url: https://www.linkedin.com/in/swsnr/

relative_links:
  enabled:     true
  collections: true
