title: Basti
description: >-
  Scala software developer. System engineer satellite mission planning. Rust. Arch.
baseurl: ""
url: ""

author:
  name: Basti
  email: sebastian@swsnr.de

# Build settings
markdown: kramdown

header_pages:
  - about.md

remote_theme: jekyll/minima
minima:
  skin: solarized
  social_links:
    - platform: github
      user_url: https://github.com/swsnr
    - platform: linkedin
      user_url: https://www.linkedin.com/in/swsnr/
