title: Basti
description: >-
  Scala software developer. System engineer satellite mission planning. Rust. Arch.
repository: swsnr/swsnr.de
url: https://swsnr.de

excerpt_separator: "<!--more-->"
show_excerpts: true

author:
  name: Basti
  email: sebastian@swsnr.de

markdown: kramdown
timezone: UTC
kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: [no_auto_typographic]
  auto_id_stripping: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
header_pages: [privacy.md]

theme: minima
minima:
  skin: solarized
  social_links:
    - platform: rss
      user_url: https://swsnr.de/feed.xml
    - platform: github
      user_url: https://github.com/swsnr
    - platform: linkedin
      user_url: https://www.linkedin.com/in/swsnr/

relative_links:
  enabled:     true
  collections: true
